root: true
env:
  es2021: true
  node: true
rules:
  quotes: 0
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "eslint-plugin-unicorn"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
